version: '3.9'

services:
  backend:
    environment:
      - COUNTRY=ch
      - DISABLE_TECH_API=true
      - LANGUAGES=fr,de,it

  frontend:
    environment:
      - COUNTRY=ch
      - LANGUAGES=fr,de,it

  nginx:
    ports:
      - "82:80"
